name: f_ui_design_template
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

#----------------- PACKAGES -----------------#

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  intl: ^0.20.2
  logger: ^2.5.0
  lottie: ^3.3.1
  url_launcher: ^6.3.1
  connectivity_plus: ^5.0.1
  flutter_native_splash: ^2.4.4
  
  # icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State management
  get: ^4.6.6
  get_storage: ^2.1.1

#----------------- ./ PACKAGES END -----------------#

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  #----------------- LOCAL ASSETS -----------------#
  assets:
    - assets/logos/
    - assets/images/content/
    - assets/icons/brands/
    - assets/images/banners/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/reviews/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/

  #----------------- LOCAL FONTS -----------------#
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/urbanist/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/urbanist/Urbanist-Italic.ttf
          style: italic
        - asset: assets/fonts/urbanist/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/urbanist/Urbanist-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/urbanist/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/urbanist/Urbanist-Bold.ttf
          weight: 800

